version: "3.1"

volumes:
  db-data:

services:
  mysql:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-mysql
    working_dir: /symfony
    volumes:
      - db-data:/symfony
    environment:
      - MYSQL_ROOT_PASSWORD=docker_root
      - MYSQL_DATABASE=sf4_db
      - MYSQL_USER=sf4_user
      - MYSQL_PASSWORD=sf4_pw
    ports:
      - "8306:3306"

  nginx:
    image: nginx
    container_name: ${PROJECT_NAME}-nginx
    working_dir: /symfony
    volumes:
      - .:/symfony
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"

  php-fpm:
    build: docker/php-fpm
    container_name: ${PROJECT_NAME}-php-fpm
    working_dir: /symfony
    volumes:
      - .:/symfony
#      - ./docker/php-fpm/php-ini.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini