FROM php:7.2-fpm

FROM php:7.2-fpm
RUN apt-get update && apt-get install -y \
        git \
        vim \
#        && docker-php-ext-install -j$(nproc) iconv         // for install php extension